function createfigure(YMatrix1, Y1, sensors, title1, error)
%CREATEFIGURE(YMATRIX1, Y1)
%  YMATRIX1:  matrix of y data
%  Y1:  stem y

%  Auto-generated by MATLAB on 22-Jan-2014 13:18:35

% Create figure
screen_size = get(0, 'ScreenSize');
figure1 = figure('Name',...
    'Segmentation with Neural Network and Hidden Markov Model', 'Position', [0 0 screen_size(3) screen_size(4)]);

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1,'XMinorTick','on');
%% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot1,[-0.0830117643658148 406.19924630015]);
%% Uncomment tahe following line to preserve the Y-limits of the axes
ylim(subplot1,[-6.89929328621908 16.7932862190813]);
box(subplot1,'on');
grid(subplot1,'on');
hold(subplot1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',subplot1);

if sensors == 3
    set(plot1(1),'DisplayName','X');
    set(plot1(2),'DisplayName','Y');
    set(plot1(3),'DisplayName','Z');
elseif sensors == 9
    set(plot1(1),'DisplayName','Pelvis X');
    set(plot1(2),'DisplayName','Pelvis Y');
    set(plot1(3),'DisplayName','Pelvis Z');
    set(plot1(4),'DisplayName','Thigh X');
    set(plot1(5),'DisplayName','Thigh Y');
    set(plot1(6),'DisplayName','Thigh Z');
    set(plot1(7),'DisplayName','Shin X');
    set(plot1(8),'DisplayName','Shin Y');
    set(plot1(9),'DisplayName','Shin Z');
    set(plot1(10),'DisplayName','Foot X');
    set(plot1(11),'DisplayName','Foot Y');
    set(plot1(12),'DisplayName','Foot Z');
end

% Create ylabel
ylabel('Rotation (deg/s)');

% Create title
title({title1});

% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1,...
    'YTickLabel',{'','Heel-off to Toe-off','Toe-off to Midswing','Midswing to Heel-strike','Heel-strike to Toe-down','Toe-down to Midstance','Midstance to Heel-off'},...
    'XMinorTick','on');
%% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot2,[-0.0830117643658148 406.19924630015]);
box(subplot2,'on');
grid(subplot2,'on');
hold(subplot2,'all');

% Create stem
stem(Y1,'Parent',subplot2);

% Create xlabel
xlabel('Time (frames)');

% Create title
title(strcat('Automatic segmentation - Mean squared error: ',{' '},error));

% Create legend
legend(subplot1,'show');

% Link x-axes of subplots.
linkaxes([subplot1,subplot2], 'x');
end